### ISSUE TITLE
Problems with ALT shortcuts on Chrome

### ISSUE THREAD

**Issue by Leftium** [tem-tem/shortcuts#2]
<kbd>ALT</kbd>-<kbd>Left Arrow</kbd> and <kbd>ALT</kbd>-<kbd>Right Arrow</kbd> seem to be in the [data files](https://github.com/tem-tem/shortcuts/blob/3bba8fd5ac2024751f47aa29bc2b77d9260fd968/src/data/chromeWin.json#L11-L12), but shows "This shortcut isn't registered as a default browser shortcut." on the live site (https://shortcuts-tem.vercel.app/).

(Environment: Chrome + Windows 11)

![image](https://user-images.githubusercontent.com/381217/209860383-1450e6d0-f6e9-4db2-9480-a764f985ae2d.png)

---

Also (<kbd>ALT</kbd>-<kbd>Home</kbd> isn't intercepted. (Possibly not allowed by browser?)

**Comment by tem-tem** [comment]
@Leftium  thanks for bringing it up! will fix soon

**Comment by tem-tem** [comment]
addressed in https://github.com/tem-tem/shortcuts/commit/8b4692af964fbfa7ce227c9dd265cf631e35af45 🙌
