### ISSUE TITLE
Ctrl + l missing / not displayed

### ISSUE THREAD

**Issue by Jan-Koll** [tem-tem/shortcuts#3]
The shortcut `Ctrl` + `l` is not listed as a result. 
![image](https://user-images.githubusercontent.com/56769801/221697034-8acaa61d-3154-451b-9552-fb3743c7f915.png)

I have only gone over some parts of the code and found that e.g. [`src/data/chromeWin.json`](https://github.com/tem-tem/shortcuts/blob/ff0969b9e8e263be5407dfcdf8f280a6f647e258/src/data/chromeWin.json#L44) the shortcut is stored (but still not shown as a result on the live page). Maybe a bug in the matching? In Firefox-Windows ([`src/data/firefoxWin.json`](https://github.com/tem-tem/shortcuts/blob/ff0969b9e8e263be5407dfcdf8f280a6f647e258/src/data/firefoxWin.json)), however, the shortcut does not seem to be listed at all, even though [it is also a default shortcut](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly).

I have not tested or checked whether this problem occurs with other browsers, shortcuts or on other devices.

Environment: Windows 10 - Edge (Chromium)

**Comment by tem-tem** [comment]
Hey! Huge thanks for finding this. You right, the regex was bugged. I went for more simple version of the regex, and made the formatting for json more defined, and also cleaned up shortcuts themself - shoutout to @Sergushka for making a PR: #4 
With the #5 this issue is resolved. Feel free to re-open, if something still bugged, @Jan-Koll

**Comment by Jan-Koll** [comment]
@tem-tem Hey there! Yes, it seems to be working now, thank you. However, I think the displayed shortkeys for `Ctrl` + `L` are not quite right for Firefox. This should have the same functionality as in Chrome ("jump to addressbar") and is also working on windows. `Ctrl` + `Shift` + `L` does not exist as far as I know (but I may be wrong here).

![image](https://user-images.githubusercontent.com/56769801/230182154-82a1090d-1099-4381-bc63-407e9a6e32d2.png)
